### ISSUE TITLE
Не работает получение баланса с сайта через АПИ

### ISSUE THREAD

**Issue by DearFox** [feytox/SPwallet#5]
При выполнении команды /spwallet balance get в консоле  игры ошибка: 
```
[14:46:13] [Render thread/INFO]: [STDERR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 20 path $
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at name.uwu.feytox.spwallet.spapi.OnlineWallet.getBalance(OnlineWallet.java:93)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at name.uwu.feytox.spwallet.spapi.OnlineWallet.lambda$initCommand$0(OnlineWallet.java:37)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.command.client.ClientCommandInternals.executeCommand(ClientCommandInternals.java:89)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zfk000$onSendCommand(class_746.java:1908)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_44098(class_746.java)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:517)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:213)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:374)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:489)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:370)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:462)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:462)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:315)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1205)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:768)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[14:46:13] [Render thread/INFO]: [STDERR]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 20 path $
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
[14:46:13] [Render thread/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
[14:46:13] [Render thread/INFO]: [STDERR]: 	... 32 more
[14:46:13] [Render thread/INFO]: [System] [CHAT] Произошла ошибка! Проверьте правильность айди и токена, доступность сайта СП, повторите попытку позже или сообщите о баге в issue
```

**Comment by feytox** [comment]
Проблема на стороне SPworlds API. Возможно, была включена ддос-защита в момент обнаружения бага.

Закрываю.
